Use const since local variable is never mutated (#3)
Spotted thanks to trying out Zig `0.12.0-dev.1676+40b8c993f`

Example:
```
src/neural_network.zig:85:17: error: local variable is never mutated
            var activation_layers = try allocator.alloc(ActivationLayer, number_of_dense_layers);
                ^~~~~~~~~~~~~~~~~
src/neural_network.zig:85:17: note: consider using 'const'
```